Add coverage checks

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -50,7 +50,28 @@ jobs:
           version: v2.1.0
 
       - name: Run integration tests
-        run: TF_ACC=1 go test -v ./...
+        run: TF_ACC=1 go test -v ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
+
+      - name: check test coverage
+        id: coverage
+        uses: vladopajic/go-test-coverage@v2
+        continue-on-error: true # Should fail after coverage comment is posted
+        with:
+          config: .testcoverage.yaml
+
+      - name: post coverage report
+        uses: thollander/actions-comment-pull-request@v3
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          comment-tag: coverage-report
+          message: |
+            go-test-coverage report:
+            ```${{ fromJSON(steps.coverage.outputs.report) }}```
+
+      # - name: "finally check coverage"
+      #   if: steps.coverage.outcome == 'failure'
+      #   shell: bash
+      #   run: echo "coverage check failed" && exit 1
 
       - name: Get logs from application pods
         if: always()
